name: final_year_project
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  animated_bottom_navigation_bar: ^1.1.0
  fl_chart: ^0.12.2
  percent_indicator: ^4.2.2
  eva_icons_flutter: ^3.1.0
  syncfusion_flutter_charts: ^20.4.53
  lottie: ^2.2.0
  cloud_firestore: ^4.6.0
  firebase_core: ^2.11.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/
    - assets/images/profile pic.jpeg
    - assets/
  uses-material-design: true

  